#define OQMARK  RA(FSLH)
#define DEGREE  RA(SEMI)
#define BALLTX  RA(EQUAL)
#define CHECKM  RA(MINUS)
#define OEXCL   RA(N1)
#define EURO    RA(N5)
#define FEM_OR  RA(2)
#define MASC_OR RA(3)
#define A_AC    RA(X)
#define E_AC    RA(G)
#define I_AC    RA(B)
#define O_AC    RA(DOT)
#define U_AC    RA(J)
#define U_DR    RA(U)
#define N_TL    RA(N)


