manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: j-w-e
      url-base: https://github.com/j-w-e
  projects:
    - name: zmk
      remote: j-w-e
      revision: with_prs
      import: app/west.yml
  self:
    path: config
